version: 0.2
env: 
  git-credential-helper: yes
phases:
  install:
    commands:
      - git -v
      - npm install -g yarn
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    commands:
      # build js files
      - yarn build
      # build layers
      - yarn build:layers
      # produce the deployment artifacts
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET_BUILD_ARTIFACTS --output-template package.yml
      - aws s3 cp ./docs s3://$S3_BUCKET_DOCS --recursive

artifacts:
  files:
    - layers/common/**/*
    - package.yml
